### ISSUE TITLE
Status bar does not update when using mouse instead of keyboard

### ISSUE THREAD

**Issue by CyrilleB79** [qtnc/6pad2#7]
The line number in the status bar is correctly updated when moving in the text of the opened file with the keyboard (arrow keys). But it is not updated if the text cursor is moved by clicking with the mouse in the text.

Steps to reproduce eye-free (with Jaws):
1. Open a file containing text in 6pad++
2. Press JawsKey+End to hear the status bar.
-> The Cursor is located on line 1 and col 1.
3. Change to Jaws Cursor (JawsKey+PavNum-)
4. With the arrow keys, read the first lines of the text.
5. With PavNum-, click on another line than line 1.2.
6. Press JawsKey+End to hear the status bar.
-> The status bar still indicates that the cursor is located on line 1 and Col 1.
7. Turn back to PC cursor (JawsKey+PavNumPlus)
8. Move the cursor on the same line with the keyboard (left or right arrows)
9. Press JawsKey+End to hear the status bar.
-> The current line and column has been updated correctly.

**Comment by qtnc** [comment]
Thank you, this will be fixed in the next release. Status bar will be updated at each mouse release, as it is updated as each key release.
